Upstream/next release
citrix/citrix-k8s-node-controller pull request #20
Opened 2021-04-08 13:18 UTC by aroraharsh23

2021-04-09 05:27 UTC, dheerajng commented on deploy/README.md
> +Note: CNC creates "kube-cnc-router" in HOST mode on all the schedulable-nodes. These router pods creates interface on nodes and do iptable config, hence, NET_ADMIN priviledge is required for same. Th
These router pods create virtual network interface and program iptables accordingly on respective nodes where they are scheduled. These pods need to run with NET_ADMIN capability to achieve the same. Hence CNC serviceaccount must have NET_ADMIN privilege and ability to create HOST mode pods.

2021-04-09 05:27 UTC, dheerajng commented on deploy/README.md
> +    | CNI_TYPE | Mandatory | The CNI used in k8s cluster. Valid values: flannel,calico,canal,weave,cilium|
write complete Kubernetes instead of k8s

2021-04-09 05:28 UTC, dheerajng commented on deploy/troubleshoot.md
> +Quick help Guide for some of the common issues that may arise.
guide in lowercase.

2021-04-09 05:29 UTC, dheerajng commented on deploy/troubleshoot.md
> +To validate ADC and basic Node configurations, Refer the screenshots on [deployment](README.md) page.
1. Citrix ADC
2. node in lowercase
3. refer in lowercase
4. remove 'the' before screenshots

2021-04-09 05:45 UTC, dheerajng commented on deploy/troubleshoot.md
> +   NET_ADMIN priviledge and the ability to create HOST mode "kube-cnc-router" pods.
correct spelling of "privilege"

2021-04-09 05:45 UTC, dheerajng commented on deploy/troubleshoot.md
> +   Look for any "permission" ERRORs in logs. As stated in deployment page, CNC creates "kube-cnc-router" pods    which need NET_ADMIN priviledge to do the configurations on nodes. So, CNC serviceacco
hyperlink for deployment page is needed here.

2021-04-09 05:53 UTC, dheerajng requested changes

2021-04-09 05:53 UTC, dheerajng commented on deploy/troubleshoot.md
> +This is the case wherein though services are UP, still user can't do ping from ADC to the service IP.
It is possible that user is unable to ping service IP from Citrix ADC even though services are in UP state.

2021-04-09 05:53 UTC, dheerajng commented on deploy/troubleshoot.md
> +As functionally wise, it will not cause any issue, user if required can ping with SRCIP as ADC VTEP created by CNC. User can use "-s" option to set the SRCIP to SNIP added by CNC on ADC.
It doesn't impact any functionality. User can ping with Citrix ADC's VTEP as source IP using `-S` option of ping command from Citrix ADC CLI prompt as seen below.
```ping <serviceIP> -S <vtepIP>```

2021-04-09 05:53 UTC, dheerajng commented on deploy/troubleshoot.md
> +Note: If it is absolutely required to ping with NSIP itself, then as of now, User need to remove the PBR entry or add new PBR entry for endpoint with higher priority
lowercase of "user"

2021-04-14 06:53 UTC, subashd approved these changes

2021-04-14 06:54 UTC, merged